### ISSUE TITLE
Add `Unlock Spotify Premium` patch

### ISSUE THREAD

**Issue by oSumAtrIX** [indrastorms/Dropped-Patches#45]
This was dropped https://github.com/ReVanced/revanced-patches/pull/3044 due to contribution guidelines. You can cherry pick it.

**Comment by indrastorms** [comment]
Merged. Thank you.

**Comment by indrastorms** [comment]
After adding this patch manager can't list any patches from this bundle.
Reverting the [commit](https://github.com/indrastorms/Dropped-Patches/commit/e8413ab227b29bbd43564b6a96af623de8143392) fixes the issue. So, could you look what's wrong with the commit?

**Comment by indrastorms** [comment]
@oSumAtrIX 
When when listing patches with cli
```
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patches/shared/misc/hex/BaseHexPatch
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:519)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at app.revanced.patcher.PatchBundleLoader$1.invoke(PatchBundleLoader.kt:47)
        at app.revanced.patcher.PatchBundleLoader$1.invoke(PatchBundleLoader.kt:46)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:129)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:55)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:34)
        at app.revanced.patcher.PatchBundleLoader$Jar.<init>(PatchBundleLoader.kt:102)
        at app.revanced.cli.command.ListPatchesCommand.run(ListPatchesCommand.kt:132)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.lang.ClassNotFoundException: app.revanced.patches.shared.misc.hex.BaseHexPatch
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 35 more
```

**Comment by oSumAtrIX** [comment]
Since you depend on another patches lib, either shade it or include it using -b
